[book]
authors = ["Xu Shaohua <shaohua@biofan.org>"]
language = "en_US"
src = "docs"
title = "Learn wgpu from scratch"

[output.html]
git-repository-url = "https://github.com/xushaohua/wgpu-101"
mathjax-support = true
